"""rename department

Revision ID: 3ecc5d4768bb
Revises: 0a0fc26417a9
Create Date: 2023-11-14 15:13:32.980313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ecc5d4768bb'
down_revision = '0a0fc26417a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departments", "department")
    # ### end Alembic commands ###
